### ISSUE TITLE
Conan package

### ISSUE THREAD

**Issue by zamazan4ik** [iboB/picobench#1]
Hello,
Do you know about [Conan](https://github.com/conan-io/conan)?
[Conan](http://docs.conan.io/en/latest/) is modern dependency manager for C++. And will be great if your library will be available via package manager for other developers.

[Here](https://github.com/bincrafters/conan-templates) you can find example, how you can create package for the library. 

Why we should create package even for single-header library: we need one way for getting different libraries. Maybe in far-far future you will rewrite your library into different files, and Conan will handle this automatically, user will be able to get your library easily as before.

If you have any questions, just ask :-)

**Comment by iboB** [comment]
That's a great idea, but unfortunately I have absolutely no experience with Conan. Perhaps this is a good occasion for me to do so, but I will be a while until I have the time.

I would welcome a pull request :)

**Comment by ZaMaZaN4iK** [comment]
On Slack we have several Conan channels: [cpplang.now.sh](cpplang.now.sh) , #conan and #bincrafters channels

**Comment by ZaMaZaN4iK** [comment]
https://github.com/bincrafters/conan-picobench

Please, if you are interested in supporting Conan package for your library (i  hope you are interested in :-) , update this Conan package every picobench release.

**Comment by iboB** [comment]
So I added a new version. How do I update the package?

**Comment by ZaMaZaN4iK** [comment]
Just update library version in conanfile.py and test package locally.

**Comment by iboB** [comment]
stale
