### ISSUE TITLE
Compilation error on Windows GCC

### ISSUE THREAD

**Issue by aandrejevas** [iboB/picobench#12]
![image](https://user-images.githubusercontent.com/53169542/234254206-a7c58569-d164-4044-bb31-7151606621cc.png)
Hello, I am getting this error when compiling with gcc.

![image](https://user-images.githubusercontent.com/53169542/234254296-eb20cd2c-5630-480b-bcfb-20d9e6e4ac3e.png)
This is the compiler I am using.

![image](https://user-images.githubusercontent.com/53169542/234254446-b5163f69-83d7-4eba-be2b-fa94855fdd71.png)
The problem seems to be that `q` type is deduced to be `char*`, so later it can not be assigned from `p` which has type `const char*`.

![image](https://user-images.githubusercontent.com/53169542/234255327-985647f2-dfb9-47d1-83dc-fdb91cd30e5e.png)
`q` type is deduced to be `char*` because `strchr` return type is `char*` in this case.

**Comment by iboB** [comment]
indeed. I have no idea why this compiles on the CI

**Comment by iboB** [comment]
Right. Thanks. Still no idea why the CI handles it, but fixing. Will tag and make a release tomorrow
